name: timcox
favicon: null
layout_spectrum: 0.45667721796780825
typography_spectrum: 0.8878545509651303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.02327674417756498
  lightness: 0.79612697660923
  saturation: 0.9068588826339692
  rhythmicContrast: 0.6360417299438268
purpose: []
